### ISSUE TITLE
Create a plugin management plugin

### ISSUE THREAD

**Issue by zach-herridge** [PoeStack/poestack-sage#13]
We need a plugin that lets people:
- View a list of current plugins
- Enabled/disable plugins
- View a list of available plugins to install
- Install/uninstall plugins

**Comment by C3ntraX** [comment]
Other features:
plugins as folder

`example-stashview-plugin`
`example-stashview-plugin/manifest.json`
`example-stashview-plugin/[chunks]` => Created by lazy imports -> `import(***)`
