### ISSUE TITLE
Expand the poe-log-service defined events

### ISSUE THREAD

**Issue by zach-herridge** [PoeStack/poestack-sage#32]
Explore the Client.txt file and add more events like https://github.com/PoeStack/poestack-sage/blob/main/src/echo-common/src/poe-log-service.ts#L32 so there is less manual parsing needed in plugins.

Add any useful events you find from looking at your Client.txt

**Comment by kongsgaard** [comment]
I am currently working on this.

I need some way of persisting settings (location of client.txt file as an example), for now i will just write it to a JSON file and pull it from there. We should have some general settings view for the commons app, which extends with plugin specific settings as they are installed
