### ISSUE TITLE
ctrl + c is no longer killing the the app

### ISSUE THREAD

**Issue by zach-herridge** [PoeStack/poestack-sage#38]
<img width="747" alt="image" src="https://github.com/PoeStack/poestack-sage/assets/6809142/ddbb21b0-b865-4f03-886e-32f3002fc4db">

Run with `npm run dev` type `ctrl + c` in terminal it crashes but doesn't actually close anymore

**Comment by C3ntraX** [comment]
Sometimes you have to press “Ctrl + C” several times until it actually closes.
Its wreid, I know
